#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")"

source lib/lib.sh

CLIENT_CONFIG=""

_rt_require_root

usage() {
  cat >&2 <<EOF
Usage: $0 <COMMAND> ...

  $0 client create       Create a new client
  $0 client list         List clients
  $0 client qrcode <N>   Show QR code for client N
  $0 client remove <N>   Remove client N
  $0 client update <N>   Update client N
  $0 config              Create rt.conf
  $0 install             Install
EOF
  exit 1
}

if [ $# -ge 2 ]; then
  cmd="$1-$2"
else
  cmd="${1:-}"
fi

case "$cmd" in
client-qrcode | client-remove | client-update)
  arg="${3:-}"
  if [ -z "$arg" ]; then
    echo >&2 "ERROR: No client argument."
    echo >&2
    usage
    exit 1
  fi
  _rt_require_client_config "$arg"
  _rt_load_conf
  source "lib/$cmd.sh"
  ;;

client-create | client-list | install)
  _rt_load_conf
  source "lib/$cmd.sh"
  ;;

config)
  source "lib/$cmd.sh"
  ;;

*)
  usage
  ;;
esac
